-- Part 1 of the dishes migration: schema only. Run 002a, then each 002b_* in order,
-- then 002c_questions_places.sql. Split because one 157 KB statement is more than
-- the browser SQL editor reliably accepts.
-- Generated by scripts/genSql.ts from data/*.csv — do not edit by hand.
-- Run in Supabase → SQL Editor. Replaces all rows in public.dishes.
begin;

-- 1.1 dishes: clean table
drop table if exists public.dishes;
create table public.dishes (
  id text primary key,
  "name" text,
  "name_uz" text,
  "description" text,
  "description_uz" text,
  "cuisine" text,
  "isHeavy" text,
  "hasMeat" text,
  "isHot" text,
  "isSoup" text,
  "isFast" text,
  "emoji" text,
  "image" text,
  "isSpicy" text,
  "isSweet" text,
  "isFatty" text,
  "hasVeggies" text,
  "hasCheese" text,
  "isFried" text,
  "byHand" text,
  "isSnack" text,
  "hasNoodles" text,
  "isGrilled" text,
  "isDumpling" text,
  "hasSeafood" text,
  "hasRice" text,
  "hasDough" text,
  "isSteamed" text,
  "dishType" text,
  "source" text,
  "hasChicken" text,
  "isWrap" text,
  "p_yes_calibrated" text,
  allergens jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- 1.1 dessert tags
alter table public.dishes
  add column "hasChocolate" text not null default 'no',
  add column "isCreamy" text not null default 'no',
  add column "isFruity" text not null default 'no',
  add column "isFrozen" text not null default 'no';

alter table public.dishes enable row level security;
create policy "dishes are readable by everyone" on public.dishes for select using (true);
grant select on public.dishes to anon, authenticated;

commit;
