// node scripts/genSql.ts → scripts/sql/002_dishes_questions.sql
import fs from 'node:fs';
import path from 'node:path';
import { DESSERT_TAGS, loadRawCsv, loadRawDessertTags, loadRawDishes, loadRawQuestions } from './lib/csvData.ts';

const q = (v: string | null) => (v == null || v === '' ? 'null' : `'${v.replace(/'/g, "''")}'`);
const ident = (c: string) => `"${c}"`;

const dishes = loadRawDishes();
const csvColumns = Object.keys(dishes[0]).filter((c) => !(DESSERT_TAGS as readonly string[]).includes(c));
const textColumns = csvColumns.filter((c) => c !== 'id' && c !== 'allergens');

const out: string[] = [];
out.push(`-- Generated by scripts/genSql.ts from data/*.csv — do not edit by hand.
-- Run in Supabase → SQL Editor. Replaces all rows in public.dishes.
begin;

-- 1.1 dishes: clean table
drop table if exists public.dishes;
create table public.dishes (
  id text primary key,
${textColumns.map((c) => `  ${ident(c)} text`).join(',\n')},
  allergens jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- 1.1 dessert tags
alter table public.dishes
${DESSERT_TAGS.map((t) => `  add column ${ident(t)} text not null default 'no'`).join(',\n')};

alter table public.dishes enable row level security;
create policy "dishes are readable by everyone" on public.dishes for select using (true);
grant select on public.dishes to anon, authenticated;
`);

const insertCols = ['id', ...textColumns, 'allergens'];
out.push(`insert into public.dishes (${insertCols.map(ident).join(', ')}) values`);
out.push(
  dishes
    .map((d) => {
      const vals = insertCols.map((c) => (c === 'allergens' ? `${q(d.allergens || '[]')}::jsonb` : q(d[c])));
      return `  (${vals.join(', ')})`;
    })
    .join(',\n') + ';\n',
);

out.push('-- dessert tags from omnom_dessert_tags.csv (all other dishes keep the default \'no\')');
for (const r of loadRawDessertTags()) {
  const sets = DESSERT_TAGS.map((t) => `${ident(t)} = ${q(r[t] || 'no')}`).join(', ');
  out.push(`update public.dishes set ${sets} where id = ${q(r.id)};`);
}

const questions = loadRawQuestions();
out.push(`
-- 1.2 questions
drop table if exists public.questions;
create table public.questions (
  id text primary key,
  mode text not null check (mode in ('meal', 'snack', 'dessert')),
  tag text not null,
  question_group text,
  question_ru text not null,
  subtitle_ru text,
  question_uz text not null,
  subtitle_uz text,
  applies_to text not null default 'all',
  show_if text,
  hide_if text,
  priority int not null default 5,
  emoji text,
  image text,
  icon_hint text
);
alter table public.questions enable row level security;
create policy "questions are readable by everyone" on public.questions for select using (true);
grant select on public.questions to anon, authenticated;
`);

const qCols = ['id', 'mode', 'tag', 'question_group', 'question_ru', 'subtitle_ru', 'question_uz', 'subtitle_uz', 'applies_to', 'show_if', 'hide_if', 'priority', 'emoji', 'image', 'icon_hint'];
out.push(`insert into public.questions (${qCols.join(', ')}) values`);
out.push(
  questions
    .map((r) => {
      return `  (${qCols.map((c) => (c === 'priority' ? String(Number(r[c]) || 5) : q(r[c]))).join(', ')})`;
    })
    .join(',\n') + ';\n',
);

const isReal = (r: Record<string, string>) => !r.id.startsWith('example-');
const places = loadRawCsv('places.csv').filter(isReal);
const menuItems = loadRawCsv('menu_items.csv').filter(isReal);
const placeIds = new Set(places.map((p) => p.id));
const dishIds = new Set(dishes.map((d) => d.id));
for (const m of menuItems) {
  if (!placeIds.has(m.place_id)) throw new Error(`menu_items.csv ${m.id}: unknown place_id ${m.place_id}`);
  if (!dishIds.has(m.dish_id)) throw new Error(`menu_items.csv ${m.id}: unknown dish_id ${m.dish_id}`);
}
const num = (v: string) => (v.trim() === '' || !Number.isFinite(Number(v)) ? 'null' : String(Number(v)));
const bool = (v: string) => (v.trim().toLowerCase() === 'false' ? 'false' : 'true');

out.push(`
-- places & menu items («Что рядом?», «Локации»)
drop table if exists public.menu_items;
drop table if exists public.places;
create table public.places (
  id text primary key,
  name text not null,
  district text,
  address text,
  lat double precision,
  lng double precision,
  express24_url text,
  yandex_eda_url text,
  is_active boolean not null default true
);
create table public.menu_items (
  id text primary key,
  place_id text not null references public.places(id) on delete cascade,
  dish_id text not null,
  price integer,
  url text
);
create index menu_items_dish_id_idx on public.menu_items (dish_id);
alter table public.places enable row level security;
alter table public.menu_items enable row level security;
create policy "places are readable by everyone" on public.places for select using (true);
create policy "menu items are readable by everyone" on public.menu_items for select using (true);
grant select on public.places, public.menu_items to anon, authenticated;
`);
if (places.length) {
  out.push('insert into public.places (id, name, district, address, lat, lng, express24_url, yandex_eda_url, is_active) values');
  out.push(places.map((p) => `  (${q(p.id)}, ${q(p.name)}, ${q(p.district)}, ${q(p.address)}, ${num(p.lat)}, ${num(p.lng)}, ${q(p.express24_url)}, ${q(p.yandex_eda_url)}, ${bool(p.is_active)})`).join(',\n') + ';\n');
}
if (menuItems.length) {
  out.push('insert into public.menu_items (id, place_id, dish_id, price, url) values');
  out.push(menuItems.map((m) => `  (${q(m.id)}, ${q(m.place_id)}, ${q(m.dish_id)}, ${num(m.price)}, ${q(m.url)})`).join(',\n') + ';\n');
}

out.push(`-- history: which mode produced the pick
alter table public.history add column if not exists mode text;

commit;
`);

const target = path.join(import.meta.dirname, 'sql', '002_dishes_questions.sql');
fs.writeFileSync(target, out.join('\n'));
console.log(`Wrote ${target}: ${dishes.length} dishes, ${questions.length} questions, ${places.length} places, ${menuItems.length} menu items`);
